# Generated by Django 4.2.7 on 2025-05-22 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='platform',
            field=models.CharField(choices=[('LeetCode', 'LeetCode'), ('GFG', 'GeeksforGeeks'), ('Codeforces', 'Codeforces')], default='LeetCode', max_length=20),
        ),
        migrations.AlterField(
            model_name='problem',
            name='status',
            field=models.CharField(default='Unsolved', max_length=20),
        ),
        migrations.AlterField(
            model_name='problem',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
